### ISSUE TITLE
Timezone issue with metadata fields

### ISSUE THREAD

**Issue by gnilrets** [jmriego/pipelinewise-target-bigquery#113] opened 2022-05-24 23:05 UTC
I've got a tap that is supplying the `time_extracted` field in UTC, `"time_extracted": "2022-05-24T23:00:12.949096Z"`.  The tap/target is running on a machine in US Pacific.  After the data gets loaded into BigQuery, it looks like the `_sdc_extracted_at` field assumed that the `time_extracted` field was in US Pacific, instead of UTC.

![image](https://user-images.githubusercontent.com/2371577/170145745-7bdb51e0-fb6e-48e7-a6c9-75d05a1d4878.png)

**Comment by edgarrmondragon** [comment] 2022-05-25 00:23
I think this is because the code [here](https://github.com/jmriego/pipelinewise-target-bigquery/blob/92b30aafe297e8ec02579388e0364097be97c29f/target_bigquery/stream_utils.py#L99-L100) creates a naive datetime object even though the timestamp is clearly UTC based on the trailing `Z`.

**Comment by gnilrets** [comment] 2022-05-25 01:09
I thought that too, but if I plop it out of the package and run that method in isolation, it seems to work as expected.  I don't see any other timezone setting anywhere else though....

**Comment by jmriego** [comment] 2022-06-02 20:24
hi @gnilrets , do you mind attaching a minimum example here? I mean the output of the tap with just a few rows so I can pipe it into this target and debug it a bit easier

**Comment by jmriego** [comment] 2022-06-02 21:51
yes, I was able to find this too. The issue is exactly as @edgarrmondragon mentioned. So the datetime object should have the UTC timezone if the field ends in "Z".
I just used the dateutil library and this is fixed now. Let me know if you find any issues with it but I think we can close this issue

**Closed as completed** 2022-06-24 16:31 UTC
